### ISSUE TITLE
Stop a script

### ISSUE THREAD

**Issue by Rolias** [idleberg/vscode-applescript#29]
This extension is great, thank you for writing it. The one thing I wish it had was a Stop Script button like Apple's script editor. I  was doing repeat until and sometimes things would hang up. A trip to the Activity Monitor allowed me to kill the wayward process but a stop button would have been a welcome convenience. It would also be nice to have indentation formatting support but I get the feeling that is probably a much bigger deal.

**Comment by idleberg** [comment]
As far as I can tell, this should be possible. However, I don't think it's possible to differentiate the process, so a stop button would kill all `osascript`/`osacompile` processes launched by the extension.

**Comment by idleberg** [comment]
> However, I don't think it's possible to differentiate the process, so a stop button would kill all osascript/osacompile processes launched by the extension.

It might actually possible, since spawned processes have a unique ID

**Comment by johans3** [comment]
+1 for this request
Vscode is a much better environment to develop a variety of code

**Comment by idleberg** [comment]
I finally got around to investing in this. A seemingly easy task, but so far it didn't work.

**Comment by idleberg** [comment]
There's a new branch [`feature/kill-process`](https://github.com/idleberg/vscode-applescript/tree/feature/kill-process) in which I'm testing this feature. While killing the process works, the UX is far from satisfying.

I went for a message dialog, but these can't be close programmatically.

The other option I'm thinking about is a button near the run/compile buttons. This would to trigger a dropdown-list of all the running processes spawned by this extension. I guess it's unlikely, that one would run multiple processes, but otherwise you wouldn't be able to kill the correct process.

Any thoughts?

**Comment by idleberg** [comment]
Updated the branch to use a quick pick dialog

**Comment by idleberg** [comment]
Feature added in v0.23
