### ISSUE TITLE
Add more applescript extensions support

### ISSUE THREAD

**Issue by JimiC** [idleberg/vscode-applescript#4]
According to [wikipedia](https://en.wikipedia.org/wiki/AppleScript) `.scpt, .scptd, .AppleScript` are also valid file extensions.

We are going to support `applescript` via `language id` in `vscode-icons`.

**Comment by idleberg** [comment]
Both, `scpt`and `scptd`, are binary AppleScripts that can't be opened by Visual Studio Code at this moment. Once Microsoft exposes an event to manipulate a file prior to opening (e.g. a load-equivalent to `onWillSaveTextDocument`), I will add support these formats.

**Comment by JimiC** [comment]
Fair enough. What about camelCase AppleScript?

**Comment by idleberg** [comment]
Are you sure it's necessary to support both, `.applescript` and `.AppleScript`?  Syntax is already highlighted properly for both cases. I don't mind adding it, but it seems language detection is already case-insensitive.

**Comment by JimiC** [comment]
It may has to do with vscode detection. Haven't checked it to be honest. I'll verify it and come back to you.

**Comment by JimiC** [comment]
Come to think of it again my request isn't so much about highlighting as to associate those extensions with an icon. In case they won't be added we will have to add associate them manually.

From what I know Mac and Linux are case-sensitive when it comes to file naming so I don't think `vscode` diverge from that. It will take me some time to return home to my Mac machine to verify my case.

**Comment by idleberg** [comment]
Not sure why my version of `vscode-nsis` doesn't show _any_ icon for AppleScript, but I tested it using NSIS:

![screen shot 2017-01-31 at 10 26 54](https://cloud.githubusercontent.com/assets/1504938/22459188/ec5f1b2e-e79f-11e6-9413-45d0e6b9f674.png)

**Comment by idleberg** [comment]
Just to mention it: a special case is an `.app` created with AppleScript. The AppleScript Editor can load these again for editing since they are basically just an Application folder bundling the script (`<appname>/Contents/Resources/Scripts/main.scpt`) and several resources. Since it won't be applicable to make a difference between a standard application and an AppleScript application, `.app` should generally use the icon designed for applications. I guess, that a prior version of `vscode-icons` used the Apple icon for both, AppleScript and macOS applications.

As for `scpt` and `scptd`, you could go on and include both extensions as binary files. Once Visual Studio Code can process files prior to loading them in the editor (e.g. for decoding binary AppleScript bundles), we can change that icon to AppleScript.

**Comment by JimiC** [comment]
1. `.app` will be moved to `binary` icon.
2. OK. We'll associate `.scpt` and `.scptd` to the `binary` icon.

Thanks a lot for your input.
